name: Fortran and Python Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gfortran
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran

      - name: Compile and Run Fortran
        run: |
          gfortran main.f90 -o simulation
          ./simulation

      - name: Run Python Plotting
        run: |
          pip install numpy matplotlib
          python plot.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: simulation-plot
          path: output.png
